### ISSUE TITLE
Changed file name has wrong color

### ISSUE THREAD

**Issue by bartkummel** [snowe2010/solarized-jetbrains#11]
If a file is changed (and version control is active), the file name gets another color in the side bar. In the solarized dark theme, this color is illegible on the dark background.
![Schermafbeelding 2019-07-12 om 14 12 42](https://user-images.githubusercontent.com/20771942/61127459-a0789580-a4af-11e9-8a06-0ec7a1d40b4b.png)

**Comment by snowe2010** [comment]
Hi bart, sorry for the massive delay in response. Github apparently decided I didn't want notifications for my own repository so I didn't even realize I had all these issues open. Could you take a look at the recent versions? This should have been fixed a while back, but if not, wait a few days and update to 3.0.0 which I just submitted for approval today.

**Comment by bartkummel** [comment]
In 2.1.0 the color is still wrong. 3.0.0 still isn't approved.
![Schermafbeelding 2019-09-20 om 13 28 14](https://user-images.githubusercontent.com/20771942/65323860-d2daf900-dbaa-11e9-91a4-6505e885eae3.png)

**Comment by snowe2010** [comment]
@bartkummel 3.0.0 was finally approved (bout an hour ago). Go ahead and try with that version and let me know if you still see the issue!
